angular/angular-ja

public/_includes/_main-nav.jade, public/_includes/_scripts-include.jade, public/docs/ts/latest/glossary.jade, public/localization/translate.js, public/resources/css/_translate.scss, public/resources/css/main.scss, public/resources/js/controllers/app-controller.js
@laco0416 please review me.
このPRの内容は次の通りです。
- 英語トグル機能を有効化 #4
- サンプルで用語集を少し翻訳してみた
トグル機能はこんな感じで動きます。
=> 英語トグル機能を有効化

public/docs/ts/latest/glossary.jade
=> docs(glossary): ObservableからZoneまで翻訳

public/docs/ts/latest/guide/_data.json, public/docs/ts/latest/guide/index.jade
翻訳のチェックをお願いします。
この章は翻訳が完了しているか？
はい（pr_state: PLEASE_REVIEW）
このPRには何が含まれますか？
翻訳
それ以外に伝えておきたいこと
- <live-example name="architecture">動作例</live-example> と書いて、リンクが張られたまま日本語訳を表示できたのでそうしている。
- #{_liveLink} -> 動作例へのリンクとした。
- 訳語では表の見出しのレイアウトが崩れるため、`<b style="white-space: nowrap">クイックスタート</b>`と、一箇所だけインラインスタイルシートを挿れた。Slackでは英語のままにするのもよいとの議論があったが、訳文の中で見出しを指し示すことやナビゲーションリンクにおける訳とも合わせるために、ここでも日本語に訳したため。
インラインスタイルシートはこの１箇所にしか適用していないため、将来のUpstreamの変更への対応の負担は軽いと思われる。
=> docs(basic/overview)を翻訳

aio-ja/content/examples/toh-pt6/src/app/hero-search/hero-search.component.ts, aio-ja/content/examples/toh-pt6/src/app/heroes/heroes.component.html, aio-ja/content/examples/toh-pt6/src/hero.service.ts, aio-ja/content/tutorial/toh-pt6.md
tutorial/top-ph6.mdの翻訳をしたので、レビューお願いしますm(_ _)m
issue: #58
=> tutorial/toh-pt6.md の翻訳

aio-ja/content/tutorial/toh-pt2.md
tutorial/toh-pt2.mdを日本語に翻訳しました。
レビューお願いいたします。
#54
=> translate: tutorial/toh-pt2.md

aio-ja/content/guide/cheatsheet.md
guide/cheatsheet.md ( #71 ) を翻訳しました。
レビューをお願いします 🙇
=> guide/cheatsheet の翻訳

aio-ja/content/marketing/index.html
=> translate(marketing/index.html): translate top page

aio-ja/content/tutorial/toh-pt5.md
tutorial/top-ph5.md を日本語に翻訳しましたので、レビューお願いします。
issueへのリンク
#61
=> translate: tutorial/toh-pt5.md

aio-ja/content/guide/http.md
=> translate: http.md

aio-ja/content/guide/service-worker-getting-started.md, prh.yml
related to #97 
- `訳注`を2つ入れています。（余計な気もするから採用するかは判断お願いします。）
- textlintの`Service Worker`ルールに`ServiceWorkerModule`などの固有名詞が引っかかります。
=> translate(content): service-worker-getting-started.md

aio-ja/content/guide/service-worker-intro.md
to fix #97
1ページ目も最後の「次の紹介記述」を統一しました。
見出し「AngularにおけるService Worker」のセクションはそのままにしています。一般的なService WorkerとAngular Serivce Workerを区別して説明しているところなので、今の方が明快で読み易いと思ったからです。
=> translate(content): unify name of index to 'Angular Service Worker'

aio-ja/content/guide/setup.md
度々すみません。
本文中のファイル名の修正です。
`text.ts` => `test.ts`
=> fix: typo setup.md

aio-ja/content/guide/observables.md
refs: #346
一行だけ英文が残っていたので翻訳しました
文中でpublishの翻訳に表記ゆれがあり、
公開する、パブリッシュする、購読する
といった表記で迷いましたが、直前で`公開する`となっていたのでそれに合わせました。
=> guide/observables.md の翻訳

aio-ja/content/guide/architecture-components.md
- コンパニオンテンプレート -> 対となる〜
- 表記ゆれ: フォーム -> 形式
- コンポネ親子関係を明確に
- ngModelとの双方向 -> ngModelを用いて〜
軽微な修正です。よろしくお願いいたします。
=> 軽微な修正: guide/architecture-components.md

aio-ja/content/marketing/events.html
`https://angular.jp/events` からイベントを調べようとする人たちは、古いイベントより新しいイベントのことを知りたいと思うので、イベントを新しいものから並べ替えてみましたがいかがでしょうか？
不要であれば PR を削除いただければと思います。
=> イベントを新しいものから並べるようにしました

aio-ja/content/guide/aot-compiler.md
- fix: Angularメタデータを指定 -> Angular メタデータを指定
- fix: TypeScript設定ファイル -> TypeScript 設定ファイル
- fix: _once_ -> _1回_ 
- fix: _factory_ -> _ファクトリ_
- fix: subset -> サブセット
- fix: 機能 -> 関数
- fix: 2 つのフェーズにすると AOT コンパイラについて考えるのに役立ちます。 -> AOT コンパイラには2つのフェーズがあると考えるとわかりやすくなります。
=> fix: guide/aot-compiler: 軽微な修正

aio-ja/content/guide/lazy-loading-ngmodules.md
原文更新部分を翻訳しました。レビューをよろしくお願いいたします。
なお、この時点の原文はコード例などで少し整合性がありませんが、下記で改善されています。
https://github.com/angular/angular/pull/33070
本家に追いついたら別途プルリしようと思います。
=> fix: guide/lazy-loading-ngmodules.md: 原文更新を翻訳

aio-ja/content/guide/structural-directives.md
`ngModdel` -> `ngModel` のタイポ修正を行いました。
=> fix: typo in guide/structural-directives.md

aio-ja/content/tutorial/toh-pt5.md
以下の英語表記が残っていた（日本語と併記されていた）ので削除しました。
"Since AppRoutingModule already imports HeroesComponent, you can use it in the routes array:"
=> 英語表記が残っていたので削除

aio-ja/content/tutorial/toh-pt5.md
Missing closing tag for `<code-example>` is causing code block disappeared.
Fix this by adding closing tag in reference of the original source.
=> Fix missing closing tag for `<code-example>` in `tutorial/toh-pt5`

aio-ja/content/guide/lifecycle-hooks.md
Fix typo `ngAfterContentChecke` to `ngAfterContentChecked` at line 165 in lifecycle-hooks.md
165行目について `ngAfterContentChecke()`は `ngAfterContentChecked()`  が正しいかと思います。
=> Fix typo in docs

aio-ja/content/guide/property-binding-best-practices.en.md, aio-ja/content/guide/property-binding-best-practices.md
=> translate: guide/property-binding-best-practices.md

aio-ja/content/start/index.md
AngularのGetting Startedをやってみたところ、StackBlitzのサンプルが開きませんでした。
live-exampleのタグは残したままで良いのかなど、修正が曖昧で申し訳ありません。
初心者からするとサンプルがすぐ開けた方が勉強しやすいかなと思うので、ご検討よろしくお願い致します（本家のドキュメントではリンクで開けました）。
=> Getting StartedのStackBlitzのサンプルのリンクが設定されていない

aio-ja/content/navigation.json
ドキュメントメニューの、サイドバー階層が英語版と異なっています。
英語版ではトップレベルにある「Angularツール」と「チュートリアル」が、「ベストプラクティス」下になっています。
そのためか、「Angularツール => 開発ワークフロー => AOT Compiler」下のメニューのインデントが崩れています。
navigation.jsonの「Angularツール」と「チュートリアル」の位置をずらして、他の内容は変えていません。
ご確認よろしくお願いいたします。
=> 訂正: navigation.json: サイドバー階層を英語版に合わせる

aio-ja/content/start/index.md
ダッシュで挟まれた「`ProductAlertsComponent`ではなく」の修飾文が不自然に係っていたので訂正させていただきました。
=> 軽微な訂正: start/index.md

aio-ja/content/guide/service-worker-devops.md
guide/service-worker-devops.md の未翻訳部分を翻訳しました。
また、一部見出しの表記揺れを統一しました。
お手隙の際にレビューをお願いします。
#489
* 246行目以降のlocationの訳し方
原文ではリダイレクト周りの話をしていて、`新しいlocationにリダイレクトする`といったような使い方をしています。
英語ではlocationで分かるのですが、日本語だと場所や位置というよりURLという意味合いが強いと感じ`場所(URL)`という訳に 
しています。こちらご意見伺いたいです。
=> translate: guide/service-worker-devops.md

docker-compose.yml
docker-compose環境への変更、お疲れ様でした。
NFSでマウントしている等の環境では、自動の再ビルドが行われないようです。(NFSか否かの違いだけで確認しています)
chokidarの`usePolling`オプションに対応する環境変数`CHOKIDAR_USEPOLLING`を`true`に変更すると、自動の再ビルドが機能しました。
https://github.com/paulmillr/chokidar#performance
https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_availability
- 無関係の環境では、パフォーマンス的にデフォルト`false`のままが良いようです
差し支えなければ、dockerに環境変数を渡せるようにYAML変更すると、下記のように実行できて便利です。
```bash
export CHOKIDAR_USEPOLLING=true
yarn start
```
ご検討よろしくお願いいたします。
=> 環境変数追加(NFS用): chokidarのusePolling

aio-ja/content/start/start-data.md
変更点は以下の3点です。
1. 112行目(「カートコンポーネントを設定する」のStep3)の以下部分が後続のStep4と重複する形で翻訳されていたため、微修正。
　原文：Update the Checkout button so that it routes to the `/cart` URL.
2. 118行目(「カートコンポーネントを設定する」のStep4)だけ`チェックアウト`になっていたため、デフォルトの`Checkout`に統一。
3. 129行目(「カートのアイテムを表示する」のStep1)の冒頭の`が抜けており、インラインコードが崩れていたため微修正。
=> [fix] start-data

aio-ja/content/guide/interpolation.md
#746
* 原文L9: HTMLコメントの部分は、触れずにそのままにしております。
* 原文L13・L17: 原文では文章の末尾が「:」ですが、下記のページを参考に、和訳版では末尾を句点にする形で反映しております。
* https://angular.jp/guide/two-way-binding
* 原文L27: 「What's Next」は、下記ページと同様に、和訳版では「次へ進む」という表記にしております。
* https://angular.jp/guide/architecture
=> translate: guide/interpolation

aio-ja/content/guide/image-directive-setup.en.md, aio-ja/content/guide/image-directive-setup.md
#767
* 原文L3: 「Getting Started with NgOptimizedImage」は、下記画面を参考に、同様の言い回しとしております。(〜を始める)
* https://angular.jp/guide/service-worker-getting-started
* 遷移先の画面が未翻訳のため、(grep 出来るように) 敢えて英語のままにしておいた方が良いなど有るでしょうか？
* 原文L7: こちらも未翻訳画面への導線となるテキストのため、敢えて英語のままにしておいた方が良いなど有りましたら修正いたします。
* 原文L11: 「画像変換URL」と「適切な場合」が、もしかすると多少意訳しなければ分かり辛いかもしれないのですが、一旦機械翻訳ベースでそのまま反映しております。
* 原文L17: 一旦機械翻訳ベースでそのまま反映しているのですが、「Angular を使用して画像を提供するサイトは、このローダーの主な使用例です」の意味がやや分かりづらく、ニュアンス的には、Angularを使って、画像を配信するCDNそのものを作るような場合、ということになるでしょうか？
* 原文L26: よく見ると原文 Markdown のテーブルのパイプが 1 つ多いのですが、表示に影響が無いことと、差分を統一する意図で、和訳版 Markdown でも修正せずそのままにしております。
* 原文L75〜77: `yoursite` を `あなたのサイト` のような形で、日本語に変換して和訳版 Markdown に反映しておりますが、それだけの対応だと、実際にブラウザで表示した際、自動でリンクに変換されず通常テキストとして表示されるようでしたので、英語サイトと同じようにリンクとして表示させるため、和訳版 Markdown では英語版 Markdown …
=> translate: guide/image-directive-setup

aio-ja/content/guide/change-detection-zone-pollution.en.md, aio-ja/content/guide/change-detection-zone-pollution.md
#759
- L.1 Zone Pollution: `Zone 汚染` と翻訳したが `汚染` のニュアンスが強すぎないか気になりました(が他の訳が思いつかず…)
- L.24 given piece of code: `指定されたコード片` とするには違和感があったので `piece of` の意味が欠けていますが `指定されたコード` と翻訳しました
- L.37 Angular Zone: 原文の表記ゆれです。(L.9, L.39 と異なり)ここだけ `Angular Zone` の Z が大文字でしたがそのまま翻訳しています
=> translate: guide/change-detection-zone-pollution

aio-ja/content/guide/typed-forms.en.md, aio-ja/content/guide/typed-forms.md
#762
- 日英2ファイルとも更新しております。(= `.en.md` も、ローカルの origin のそれと差分が有ったため、angular/angular リポジトリの方から直接ファイルコピーする形で取得したものをコミットし、その`.en.md` をもとに日本語版の md ファイルを作成しております)
- 原文L1: `Typed Forms` をそのまま表記するか、`型付きフォーム` のように和訳した表記とするか。
- (Angular の用語としてある程度一般的かと思い) 一旦 `Typed Forms` で反映しております。
- 原文 ~L40~ L42: `Untyped Forms` をそのまま表記するか、`型指定されていないフォーム` のように和訳した表記とするか。
- (用語としてあまり一般的ではないかと思い) 一旦 `型指定されていないフォーム` で反映しております。
=> translate: guide/typed-forms

aio-ja/content/guide/change-detection-skipping-subtrees.en.md, aio-ja/content/guide/change-detection-skipping-subtrees.md
#761
- 原文 ~L14~ L72: `〜な場合` という言い回しでL13と言い回しを揃えた方が自然かと思い、言葉の順番入れ替え的な意訳が入っております。
=> translate: guide/change-detection-skipping-subtrees

aio-ja/content/guide/pipe-template.en.md, aio-ja/content/guide/pipe-template.md
https://github.com/angular/angular-ja/issues/753
他のドキュメントを見たりはしましたが、初参入なので、
このプロジェクトでの用語や言い回しが認識あっているか(expression、operator、look atなど)を
重点的にレビューしていただければと思います。
=> 20240115 pipe-templateの和訳作成

.github/workflows/adev-preview-build.yml, .github/workflows/adev-preview-deploy.yml, .github/workflows/adev-production-deploy.yml, .github/workflows/build-and-test.yml, tools/adev-patches/change-analytics-id.patch, tools/adev-patches/change-document-title.patch, tools/adev-patches/localize-home.patch, tools/build.mjs, tools/lib/common.mjs
Adding initial workflows for adev build and deploy.
=> chore: add initial workflow for adev build

tools/adev-patches/resolve-angular-docs-build-version.patch
Temporary version resolution to preview #949 . Remove this patch when the origin includes it.
=> chore: use temporal angular/docs version patch to extract header id

adev-ja/src/content/guide/forms/dynamic-forms.en.md, adev-ja/src/content/guide/forms/dynamic-forms.md, adev-ja/src/content/guide/forms/form-validation.en.md, adev-ja/src/content/guide/forms/form-validation.md, adev-ja/src/content/guide/forms/overview.en.md, adev-ja/src/content/guide/forms/overview.md, adev-ja/src/content/guide/forms/reactive-forms.en.md, adev-ja/src/content/guide/forms/reactive-forms.md, adev-ja/src/content/guide/forms/template-driven-forms.en.md, adev-ja/src/content/guide/forms/template-driven-forms.md, adev-ja/src/content/guide/forms/typed-forms.en.md, adev-ja/src/content/guide/forms/typed-forms.md, prh.yml
=> fix: translate forms guides

adev-ja/src/content/guide/performance/overview.en.md, adev-ja/src/content/guide/performance/overview.md
=> fix: translate performance guides

adev-ja/src/app/features/update/update.component.en.html, adev-ja/src/app/features/update/update.component.en.ts
=> fix: translate update guide

.firebaserc, .github/workflows/adev-production-deploy.yml, firebase.json
Cloudflare Pagesの変更不可能なtrailing slash redirectの仕様がAngularのprerenderと相性が悪いため、Firebase Hostingへ戻すことを検討している。
=> chore: re-add deployment to Firebase

firebase.json
https://firebase.google.com/docs/hosting/full-config?hl=ja
`/about/index.html` が存在するとき、 `/about` へのリクエストを自動的に `/about/` にリダイレクトする振る舞いを無効にする
=> chore: disable adding trailing slash by firebase hosting

.github/workflows/adev-preview-build.yml, .github/workflows/adev-preview-deploy.yml
Use the github event values instead of the user generated information.
=> ci: update adev-preview-deployment to no longer use metadata from build output

adev-ja/src/app/sub-navigation-data.ts, adev-ja/src/content/guide/hybrid-rendering.en.md, adev-ja/src/content/guide/hybrid-rendering.md, adev-ja/src/content/guide/performance/overview.md
=> fix: translate guide/hybrid-rendering.md

adev-ja/src/app/features/update/recommendations.ts, tools/translate.ts
=> fix: translate v19 update guide

adev-ja/src/content/best-practices/runtime-performance/overview.en.md, adev-ja/src/content/best-practices/runtime-performance/overview.md, tools/translator/agent.ts, tools/translator/main.ts
=> feat: translate runtime-performance/overview.md

adev-ja/src/content/guide/routing/router-tutorial.en.md, adev-ja/src/content/guide/routing/router-tutorial.md
=> feat: translate router-tutorial.md

tools/translator/agent.ts
This pull request includes a small change to the `tools/translator/agent.ts` file. The change updates the `defaultGeminiModel` to use a newer variation of the Gemini model, with a comment linking to the official documentation for model variations.
=> fix: update default Gemini model to the latest version

adev-ja/src/content/guide/animations/enter-and-leave.en.md, adev-ja/src/content/guide/animations/enter-and-leave.md
=> feat: translate animations/enter-and-leave.md

adev-ja/src/content/guide/animations/enter-and-leave.md
=> fix: remove unnecessary IDs from section headers in animations documentation

adev-ja/src/content/ai/develop-with-ai.md
Fix heading ID formatting by removing dots from the anchor ID as per translator guidelines.
- Fixed heading ID from `#providing-context-with-llms.txt` to `#providing-context-with-llmstxt` in `adev-ja/src/content/ai/develop-with-ai.md`
This follows the heading ID symbol handling rule that removes all symbols except hyphens from anchor IDs.
=> docs: fix heading ID formatting in develop-with-ai.md

adev-ja/src/content/guide/routing/overview.md
なし
- `adev-ja/src/content/guide/routing/overview.md`
=> feat(docs): translate routing overview documentation to Japanese

adev-ja/src/content/guide/routing/router-reference.md
ルーターリファレンスに関するドキュメントの日本語翻訳
翻訳したファイル:
- `adev-ja/src/content/guide/routing/router-reference.md`
=> feat(docs): translate router reference documentation to Japanese

adev-ja/src/content/tools/cli/setup-local.en.md, adev-ja/src/content/tools/cli/setup-local.md
CLIローカルセットアップに関するドキュメントの日本語翻訳
翻訳したファイル:
- `adev-ja/src/content/tools/cli/setup-local.md`
=> feat(docs): translate CLI setup local documentation to Japanese

adev-ja/src/content/tools/cli/serve.en.md, adev-ja/src/content/tools/cli/serve.md
Angular CLIの`ng serve`コマンドに関するドキュメントを日本語に翻訳しました。
- 開発用のAngularアプリケーション配信の基本的な使用方法
- バックエンドサーバーへのプロキシ設定
- localhostの名前解決に関する問題と解決方法
- コマンドライン構文とオプション
- `adev-ja/src/content/tools/cli/serve.md`: 日本語翻訳版
- `adev-ja/src/content/tools/cli/serve.en.md`: 英語原文の保存版
=> feat(docs): translate CLI serve documentation to Japanese

adev-ja/src/content/best-practices/style-guide.md
Angularコーディングスタイルガイドを日本語に翻訳しました。
- 命名規則（ファイル名、セレクター、メンバー）
- プロジェクト構造のベストプラクティス
- 依存性の注入に関するガイドライン
- コンポーネントとディレクティブの設計原則
- テンプレートとスタイルのベストプラクティス
- `adev-ja/src/content/best-practices/style-guide.md`: 日本語翻訳版
=> feat(docs): translate Angular style guide to Japanese

tools/adev-patches/add-global-styles.patch
This pull request updates the global styles patch to correctly target the `.docs-viewer` class instead of the `docs-viewer` element, which improves the specificity and reliability of the style override for Japanese headings.
* Global Styles Correction:
* Changed the selector from `docs-viewer` to `.docs-viewer` to ensure styles are applied to the intended class, addressing issues with heading balancing for Japanese content.
=> fix: correct styling for docs-viewer headings

package.json, tools/list-untranslated.ts
Add a new utility script `list-untranslated` that identifies files in adev-ja that don't have corresponding `.en.*` backup files, indicating they haven't been translated yet.
- ✅ Add `tools/list-untranslated.ts` - New TypeScript executable script that scans for untranslated files
- ✅ Add `pnpm run list-untranslated` command to package.json for easy execution
- ✅ Uses simple glob pattern to find all translatable files (`.md`, `.ts`, `.html`, `.json`)
- ✅ Excludes license files and `.en.*` backup files from scan
- ✅ Provides clear output showing count and list of untranslated files
```bash
pnpm run list-untranslated
```
Output example:
```
Found 149 untranslated files:
src/content/best-practices/error-handling.md
src/content/ecosystem/rxjs-interop/output-interop.md
...
```
This tool helps …
=> feat(tools): add list-untranslated script to identify untranslated files
