angular/angular-ja

firebase.json
@laco0416 please review me.
firebaseのURLを変更しました！
=> chore: firebaseのURLを変更

README.md
=> chore(README): change travis badge URL

README.md
=> chore(README): Wikiへのリンクを追加

public/docs/ts/latest/glossary.jade
翻訳のチェックをお願いします。
__この章は翻訳が完了しているか？__
__このPRには何が含まれますか？__
__それ以外に伝えておきたいこと__
=> docs(glossary): Ahead of Time (AOT) CompilationからComponentまで翻訳

public/docs/ts/latest/glossary.jade
翻訳のチェックをお願いします。
この章は翻訳が完了しているか？
はい（pr_state: PLEASE_REVIEW）
このPRには何が含まれますか？
翻訳
それ以外に伝えておきたいこと
なし
=> docs(glossary): EからIまでを翻訳

public/docs/ts/latest/glossary.jade
翻訳のレビューをお願いします。
**この章は翻訳が完了しているか？**
**このPRには何が含まれますか？**
**それ以外に伝えておきたいこと**
- [Just in Time (JIT) Compilation]
- `With Angular _Just in Time_  bootstrapping`を直訳っぽくしていますが、他にわかりやすい表現があればそちらを採用したいと思います。
- [Lifecycle Hooks]
- `key moments`を「契機」としていますが、これでいいのか不安です。
=> docs(glossary): JからMまでを翻訳

public/docs/ts/latest/glossary.jade
翻訳のレビューをお願いします。
**この章は翻訳が完了しているか？**
**このPRには何が含まれますか？**
**それ以外に伝えておきたいこと**
- [Barrel] コード中のコメントも訳したほうが理解がしやすいと思ったのですが、他の言語で訳されていないものがあったことと、翻訳文をどう記載したらよいかわからなかったので、訳さずにそのままにしています
- [Component] 原文では翻訳できないリンクの形式 `!{_decoratorLink}` で書かれているため decorator と表示されてしまいますがそのままにしておいています。`[デコレーター](#decorator)` と等価であれば、置き換えを検討してもいいかもしれません
- [Decorator] `The scope of a decorator is limited to the language feature that it decorates.` の the language feature の扱いは少し自信がありません
=> docs(glossary): BarrelおよびCからDまでを翻訳

prh.yml, public/docs/ts/latest/_data.json, public/docs/ts/latest/glossary.jade, public/docs/ts/latest/guide/_data.json
=> refactor(glossary): glossaryの全体的な微調整

public/docs/ts/latest/tutorial/toh-pt1.jade
翻訳のレビューをお願いします。
**この章は翻訳が完了しているか？**
**このPRには何が含まれますか？**
**それ以外に伝えておきたいこと**
- 67 行目: 原文にピリオドが抜けているためビルドが失敗します。原文にピリオドを追加しましたが問題ないでしょうか。
=> docs(tutorial): 2. The Hero Editor を翻訳

prh.yml
=> chore(prh): add prh rules

.firebaserc
```
$ firebase use live
$ firebase deploy
```
に変わっていた
=> chore(deploy): firebaseデプロイ先を変更

aio-ja/content/guide/glossary.md, aio-ja/content/navigation.json
=> glossary.mdの翻訳

aio-ja/content/tutorial/toh-pt4.md
tutorial/toh-pt4.md を翻訳しました
レビューをお願いしますm(__)m
#55
=> translate: tutorial/toh-pt4.md

aio-ja/content/guide/service-worker-communications.md
=> translate(content): service-worker-communications.md

aio-ja/src/environments/environment.archive.ts, aio-ja/src/environments/environment.next.ts, aio-ja/src/environments/environment.stable.ts, aio-ja/src/environments/environment.ts
=> fix(aio): Override Google Analytics ID

prh.yml
=> Fix typo in prh.yml

aio-ja/content/guide/animations.en.md, aio-ja/content/guide/animations.md
#84 
guide/animations の翻訳を行いました。
お手数ですが、ご確認お願いいたします。
=> Translate guide/animations.md

aio-ja/content/guide/forms.en.md, aio-ja/content/guide/forms.md
=> translate(guide): guide/formsの翻訳

aio-ja/content/guide/bootstrapping.en.md, aio-ja/content/guide/bootstrapping.md
=> translate(guide): guide/bootstrappingの翻訳

aio-ja/content/guide/pipes.en.md, aio-ja/content/guide/pipes.md
=> translate(guide/pipes): guide/pipesを翻訳

aio-ja/content/guide/service-worker-devops.md
=> translate(guide): additonal part of service-worker-devops.md

aio-ja/content/guide/attribute-directives.en.md, aio-ja/content/guide/attribute-directives.md
#87 
やると決めてから大変遅くなりました 🙇
`guide/attribute-directives`の翻訳を終えたのでレビューお願いします。
=> translate attribute-directives.md from English to Japanese

aio-ja/content/guide/http.en.md, aio-ja/content/guide/http.md
to fix #117
再翻訳です。
原文も退避しておきました（http.en.md）
=> translate(guide): retranslate http.md

aio-ja/content/guide/ngmodule-vs-jsmodule.en.md, aio-ja/content/guide/ngmodule-vs-jsmodule.md
refs: #162
guide/ngmodule-vs-jsmodule.md の翻訳です。よろしくお願いします。
=> [#162] guide/ngmodule-vs-jsmodule.md の翻訳

aio-ja/content/guide/reactive-forms.en.md, aio-ja/content/guide/reactive-forms.md
refs #144 
お待たせしました！
Reactive Forms ページの翻訳が出来ました。
よろしくお願いします！
=> translate(guide): translate reactive-forms.md

aio-ja/content/guide/releases.en.md, aio-ja/content/guide/releases.md, aio-ja/content/navigation.json
=> translate(guide/releases): guide/releasesの翻訳

aio-ja/content/guide/updating.en.md, aio-ja/content/guide/updating.md, aio-ja/content/navigation.json
=> translate: guide/updatingの翻訳

aio-ja/content/guide/elements.en.md, aio-ja/content/guide/elements.md
guide/elements.md の翻訳（#180）です。こちらでは初めて翻訳させていただきました。ご確認のほどよろしくお願いいたします。
```
<div class="l-sub-section">
We are working ...
```
の部分が本家の最新版と表示位置が異なっていましたので、最新版に合わせておきました。
=> guide/elements.md の翻訳

aio-ja/content/guide/entry-components.en.md, aio-ja/content/guide/entry-components.md
ref: #187
guide/entry-componentsの翻訳です。よろしくおねがいします!
=> translate guide/entry-components

aio-ja/src/index.html
=> Japanese translation

aio-ja/content/guide/singleton-services.en.md, aio-ja/content/guide/singleton-services.md
refs #201 
guide/singleton-serviceの翻訳です。よろしくおねがいします!
root routeあたりが苦しすぎます・・・
=> translate guide/singleton-service

aio-ja/content/guide/elements.md
refs #216
guide/elements.mdの翻訳です。よろしくおねがいします!
=> translate guide/elements

aio-ja/content/guide/architecture-components.en.md, aio-ja/content/guide/architecture-components.md, aio-ja/content/guide/architecture.md
翻訳したので一度確認お願いします。
issue link : [guide/architecture-components.md の翻訳](https://github.com/angular/angular-ja/issues/227)
=> translate guide/architecture-components.md

aio-ja/content/guide/architecture-components.md
#227
すいません余計なコマンドの文字列が入ってしまっていたので直しました。
=> fixed: clear unnecessary string

aio-ja/content/guide/dependency-injection.en.md
#249 翻訳
「注入可能な service クラスの作成」の手前までと、各セクションタイトルを翻訳
改めて
=> translate: dependency-injection.md

aio-ja/content/guide/reusable-animations.en.md, aio-ja/content/guide/reusable-animations.md
=> translate: guide/reusable-animations.md (#263)

aio-ja/content/guide/complex-animation-sequences.en.md, aio-ja/content/guide/complex-animation-sequences.md
ref: #261
一応、@ukyoさんのプルリクエスト( https://github.com/angular/angular-ja/pull/260 )を踏まえています。
よろしくおねがいします。
=> translate: guide/complex-animation-sequences.md (#261)

aio-ja/content/navigation.json
=> fix: CLIサブコマンドが表示されるように修正

aio-ja/content/guide/form-validation.md
- Add space before and after backquote, underscore
=> Add space before and after backquote

aio-ja/content/guide/styleguide.md
styleguide.md Pipe names の翻訳をしました。
Ref: #308
=> [styleguide] 命名規則の翻訳 # Pipe names

aio-ja/content/guide/styleguide.md
guide/styleguide.md の unit test file names を翻訳しました。
Ref: #308
=> [styleguide] 命名規則の翻訳 # unit test file names

aio-ja/content/guide/styleguide.md
#308 に関して、下記を訳しました。レビューよろしくおねがいします。
* 02-06 directive-selectors
* 02-08 directive-custom-prefix
=> [styleguide] naming convention for directives (#308)

aio-ja/content/guide/styleguide.md
Close https://github.com/angular/angular-ja/issues/321
=> translatre: styleguide coding conventionsの翻訳

aio-ja/content/guide/styleguide.md
Close https://github.com/angular/angular-ja/issues/325
=> translate: styleguide Components - Directivesの翻訳

aio-ja/content/guide/styleguide.md
https://github.com/angular/angular-ja/issues/308
=> translate: styleguide namingの残りを翻訳

aio-ja/content/guide/router.en.md
=> guide/routerの翻訳 (オリジナルのenファイルを追加) refs #203

aio-ja/content/guide/testing.md
=> fix: typo testing.md

aio-ja/content/tutorial/toh-pt5.md
未翻訳でしたので翻訳してみました。
（ほぼ機械翻訳頼りですが。。。）
原文に合わせるようなイメージで改行を入れております。
=> translate: tutorial/toh-pt5.md 未翻訳の注記部分を翻訳

aio-ja/content/guide/npm-packages.en.md, aio-ja/content/guide/npm-packages.md
#295
遅くなりましたが、`npm-packages`のガイドを翻訳しました。
=> translate: guide/npm-packages.md

aio-ja/content/tutorial/toh-pt2.md
チュートリアルを使って研修を行っていた際に、あれ？っと思った点を修正してみました。
ご確認いただければ幸いです。
=> chore: change of wording tutorial/toh-pt2.md

aio-ja/content/start/index.en.md, aio-ja/content/start/index.md
=> translate: start/index.md (#373)

aio-ja/content/cli/index.en.md, aio-ja/content/cli/index.md
close #378 
`cli/index.md` の翻訳を実施しました。
ご確認お願いします 😃
=> translate: cli/index.md

aio-ja/content/start/forms.en.md, aio-ja/content/start/forms.md
close #376 
（アサイン？前ですが）上記翻訳実施しましたのでPRいたします。
ご確認いただければ幸いです 😃
=> translate: start/forms.md

aio-ja/content/start/routing.en.md, aio-ja/content/start/routing.md
closed #374.
@lacolaco よろしくお願いいたします！
=> translate: start/routing #374

aio-ja/content/start/deployment.en.md, aio-ja/content/start/deployment.md
close #377 
上記翻訳実施しました 😃 
が、何箇所か意訳している部分があります。
コメントを付与しておきますのでご確認いただければ幸いです。
=> translate: start/deployment.md

aio-ja/content/start/data.en.md, aio-ja/content/start/data.md
close #375 
申し訳ありません、Draftで一旦作成してしまいました。
=> translate: start/data.md

aio-ja/content/cli/usage-analytics-gathering.en.md, aio-ja/content/cli/usage-analytics-gathering.md
close #379 cli/usage-analytics-gathering.md
上記翻訳実施しました。
ご確認をお願いいたします 😃
=> translate: cli/usage-analytics-gathering.md

aio-ja/content/guide/file-structure.md
close #381 
`guide/file-structure.md`の追加翻訳です。
=> translate: guide/file-structure

aio-ja/content/guide/workspace-config.md
close #369 
`guide/workspace-config.md`の追加翻訳です。
=> translate: guide/workspace-config.md

aio-ja/content/guide/dependency-injection.md
- インジェクション -> 注入
- HeroListComponent -> HeroComponent, inject A with B => AにBを注入
- configure FILE with VALUE => FILEにVALUEを設定
- 提供 -> provideオブジェクト
- 機能と高度な機能 -> 機能と高度な特徴
- DI イン・アクション
- ニュアンスなど
不要な部分があるかもしれませんが、よろしくお願いいたします。
=> 軽微な修正: guide/dependency-injection.md

aio-ja/content/guide/bootstrapping.md
- fix: Angularを -> Angularに
一文字ですが、よろしくお願いいたします。
=> 超軽微な修正: guide/bootstrapping.md

aio-ja/content/guide/ivy.en.md, aio-ja/content/guide/ivy.md
=> Translate ivy into japanese.

aio-ja/content/guide/web-worker.en.md, aio-ja/content/guide/web-worker.md
=> Translate web-worker into japanese.

aio-ja/content/guide/ngmodule-vs-jsmodule.md
=> 軽微な修正: guide/ngmodule-vs-jsmodule.md: 原文更新により

aio-ja/content/guide/frequent-ngmodules.md
- want toを反映、ルーティングを削除
英文が以前の更新で、want toに変えてきたので、一応反映しました。よろしくお願いいたします。
=> 軽微な修正: guide/frequent-ngmodules.md: 原文更新により

aio-ja/content/guide/feature-modules.md
- 調整 -> サイズ調整
- CustomerDashboardModule -> CustomerDashboardComponent
以上です。よろしくお願いいたします。
=> 軽微な修正: guide/feature-modules.md:

aio-ja/content/guide/accessibility.en.md, aio-ja/content/guide/accessibility.md
=> translate: guide/accessibility

aio-ja/content/guide/lazy-loading-ngmodules.md
=> 軽微な修正: guide/lazy-loading-ngmodules.md

aio-ja/content/marketing/events.html
=> docs(events): イベントを追加

aio-ja/content/guide/build.md
=> fix: guide/build: 軽微な修正

aio-ja/content/guide/displaying-data.md
- 括弧の位置移動
- iterable object -> 反復可能〜
- 行数調整など
コメント追加します。
=> fix: guide/displaying-data.md: 軽微な修正

aio-ja/content/cli/index.md
Issue番号 #467
とても短いですが，レビューお願いします
=> translate: /content/cli/index.md

aio-ja/content/tutorial/toh-pt2.md
Both English sentences and Japanese sentences are shown.
I remove English sentences.
=> Remove duplicate sentences.

aio-ja/content/guide/typescript-configuration.md
Issue: https://github.com/angular/angular-ja/issues/494
翻訳をしたので、レビューをお願いします。
=> translate: /guide/typescript-configuration

aio-ja/content/guide/universal.en.md, aio-ja/content/guide/universal.md
#259
だいぶ間が空いてしまって申し訳ないですが、少しづつ進めていきます。
=> translate before tutorial.

aio-ja/content/guide/lazy-loading-ngmodules.md
ref: #493
更新部分の翻訳と、すこし日本語を修正しました。よろしくおねがいします:pray:
=> translate: guide/lazy-loading-ngmodulesの再翻訳

aio-ja/content/start/data.md
=> fix(start): set correct code-example region

aio-ja/content/guide/ivy.en.md, aio-ja/content/guide/ivy.md, aio-ja/content/guide/lazy-loading-ngmodules.md
=> translate: guide/ivy.md (#487)

aio-ja/content/guide/template-syntax.md
#505 の一部を翻訳しました
* Binding syntax: an overview（バインディング構文: 概要）
* Binding types and targets（バインディングタイプとターゲット）
=> translate: guide/template-syntax.md のバインディング構文などを翻訳

aio-ja/content/guide/angular-compiler-options.md
=> translate rest part.

.gitignore, netlify.toml
=> fix: netlifyのSPAフォールバック設定を追加

aio-ja/content/guide/workspace-config.md
=> translate before 'Configuring builder targets'

aio-ja/content/guide/template-syntax.md
=> translate: guide/template-syntax.md Property binding

aio-ja/content/guide/displaying-data.md
=> Translate 'displaying-data' into Japanese.

aio-ja/content/guide/workspace-config.md
#490
微妙に残っていたのを見落としていました。確認お願いします。
=> Translate workspace-config into Japanese.

aio-ja/content/guide/architecture-next-steps.md
=> translate: guide/architecture-next-steps.md

aio-ja/content/guide/aot-metadata-errors.en.md
=> translate guide/aot-metadata-errors into Japanese.

aio-ja/content/guide/template-syntax.md
Attribute, class, and style bindings のセクションを和訳しました。
#505
=> translate: guide/template-syntax.md の一部

aio-ja/content/guide/template-syntax.md
#505 
やっとページの半分ぐらいまで来ました。
ありません。
=> translate: guide/template-syntax.md の組み込みディレクティブまで

aio-ja/content/guide/template-syntax.md
=> translate: guide/template-syntax.md のテンプレート参照変数まで

aio-ja/content/guide/observables.md
=> 英語の消し忘れを修正しました。

aio-ja/content/guide/schematics-authoring.en.md, aio-ja/content/guide/schematics-authoring.md, aio-ja/content/navigation.json
schema.json例内のdescriptionやx-prompt messageの内容は英文のままとしています。ご確認よろしくお願いします:bow:
=> translate: /guide/schematics-authoring

aio-ja/content/guide/template-syntax.md
=> translate: guide/template-syntax.md の残り

aio-ja/content/guide/module-types.en.md, aio-ja/content/guide/module-types.md
=> translate: guide/module-types.md

.github/workflows/build-and-test.yml
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
=> ci: use pull_request_target

build-win.ps1
Hi i make this powershell scripts for contributors that use windows ,this works since windows 8ˆ and windows server ˆ2008  to actual versions like 10 or major versions of windows serve , i hope it helps
=> feature: powershell script for windows contributors fair with master

aio-ja/content/guide/event-binding-concepts.en.md, aio-ja/content/guide/event-binding-concepts.md
=> translate: guide/event-binding-concepts.md

aio-ja/content/guide/file-structure.md
=> 軽微な修正: guide/file-structure.md

aio-ja/content/guide/template-reference-variables.en.md, aio-ja/content/guide/template-reference-variables.md
=> translate: guide/template-reference-variables.md

aio-ja/content/guide/typescript-configuration.md
=> 軽微な修正: guide/typescript-configuration.md

aio-ja/content/guide/entry-components.md
=> 軽微な修正: guide/entry-components.md

aio-ja/content/guide/glossary.en.md, aio-ja/content/guide/glossary.md
大きいファイルなことと、用語集なのでまず見出し語の翻訳を確定したく、軽微な修正で出しました。
本文の翻訳は後から少しずつ(みなさんもやりやすいかと)。
=> 軽微な修正: guide/glossary.md

aio-ja/content/guide/strict-mode.en.md, aio-ja/content/guide/strict-mode.md
=> translate: guide/strict-mode.md

aio-ja/content/guide/workspace-config.md
=> 軽微な修正: guide/workspace-config.md

aio-ja/content/guide/lazy-loading-ngmodules.md
=> 軽微な訂正: guide/lazy-loading-ngmodules.md

aio-ja/content/guide/providers.md
=> 軽微な修正: guide/providers.md

.github/workflows/deploy-preview.yml
=> ci: change deploy preview workflow to use a label

aio-ja/content/guide/build.md
=> translate guide/build into Japanese.

aio-ja/content/guide/form-validation.en.md, aio-ja/content/guide/form-validation.md
https://github.com/angular/angular-ja/issues/603
レビューよろしくお願いいたします。
=> translated: guide/form-validation.mdの翻訳

aio-ja/content/guide/component-overview.en.md, aio-ja/content/guide/component-overview.md
=> Translate guide/component-overview into japanese

aio-ja/content/guide/lifecycle-hooks.md
#622
翻訳漏れを見つけたのでその箇所のみ翻訳しています。
=> Translate lifecycle-hooks into Japanese

aio-ja/content/guide/inputs-outputs.md
=> fix: guide/inputs-outpus.md

aio-ja/content/start/start-routing.md
以下修正させていただきました。
- 不自然な助詞を修正
- インラインのcodeの開始バッククォートが欠けていたので追加
- 不自然な文章を修正
=> 軽微な修正: start/start-routing.md

aio-ja/content/tutorial/toh-pt0.md
=> docs: Fix typo in tutorial

aio-ja/content/guide/component-styles.md
=> translate: guide/component-styles.md

aio-ja/content/guide/content-projection.en.md, aio-ja/content/guide/content-projection.md, aio-ja/content/navigation.json
=> guide/content-projectionの翻訳 #654

aio-ja/content/guide/dependency-injection-providers.en.md, aio-ja/content/guide/dependency-injection-providers.md, aio-ja/content/navigation.json
=> guide/dependency-injection-providers.mdの翻訳 #661

aio-ja/content/guide/structural-directives.en.md, aio-ja/content/guide/structural-directives.md
https://github.com/angular/angular-ja/issues/667
318行目、`umbrella type` がわからず訳せませんでした。
=> translate: guide/structural-directives.md

aio-ja/content/start/index.md
=> 和訳｜子コンポーネントにデータを渡すの章

aio-ja/content/tutorial/toh-pt1.md
=> 軽微な修正： tutorial/toh-pt1

aio-ja/content/tutorial/toh-pt6.md
=> 軽微な修正: tutorial/toh-pt6

aio-ja/content/cli/cache.en.md, aio-ja/content/cli/cache.md
https://github.com/angular/angular-ja/issues/701
よろしくお願いいたします！
=> translate: cli/cache.md

aio-ja/content/guide/i18n-common-overview.en.md, aio-ja/content/guide/i18n-common-overview.md
=> translate: guide/i18n-common-overview.md

aio-ja/content/guide/security.md
=> guide/security.md の翻訳（未翻訳分の追加翻訳）

aio-ja/content/guide/i18n-common-add-package.en.md, aio-ja/content/guide/i18n-common-add-package.md
=> translate: guide/i18n-common-add-package

aio-ja/content/guide/i18n-common-locale-id.en.md, aio-ja/content/guide/i18n-common-locale-id.md
=> translate: guide/i18n-common-locale-id

aio-ja/content/guide/i18n-common-format-data-locale.en.md, aio-ja/content/guide/i18n-common-format-data-locale.md
=> translate: guide/i18n-common-format-date-locale

aio-ja/content/start/index.md
=> 軽微な修正: start/index

aio-ja/content/guide/router-tutorial.en.md, aio-ja/content/guide/router-tutorial.md
close #551
元々翻訳されていたのが https://github.com/angular/angular-ja/pull/561 で戻ってしまったようで、以前の翻訳結果を参考にPRを作りました。戻る前のコードを見たところ .en.md が無かったので、もしかしたらそのせいで戻ってしまったのかもしれません。
=> guide/router-tutorial.md の翻訳

aio-ja/content/navigation.json
=> fix: update navigation

aio-ja/content/marketing/index.html
「モダンWeb開発者のプラットフォーム」の文言が重複しておりましたので、以下原文にないタグの方削除しました。
https://github.com/angular/angular/blob/main/aio/content/marketing/index.html#L14
=> 軽微な修正: marketing/index.html

aio-ja/content/guide/creating-injectable-service.en.md, aio-ja/content/guide/creating-injectable-service.md, aio-ja/content/guide/dependency-injection-providers.en.md, aio-ja/content/guide/dependency-injection-providers.md, aio-ja/content/navigation.json
=> translate: DI関連ガイドの翻訳

aio-ja/content/guide/image-directive.en.md, aio-ja/content/guide/image-directive.md
=> translate: guide/image-directive

aio-ja/content/start/index.md, aio-ja/content/start/start-routing.md
=> fix: improve translation of getting started

aio-ja/content/guide/pipes-overview.en.md, aio-ja/content/guide/pipes-overview.md, aio-ja/content/navigation.json
=> translate: pipes-overview.md

aio-ja/content/start/start-data.md
[#803 (comment)](https://github.com/angular/angular-ja/pull/803#issuecomment-1403647895)
=> Fix start-data.md

aio-ja/content/guide/event-binding.md, aio-ja/content/navigation.json
=> fix(event-binding): イベントバインディングのガイドを翻訳

aio-ja/content/errors/NG0203.en.md, aio-ja/content/errors/NG0203.md
=> fix: translate errors/NG0203

aio-ja/content/start/index.md
=> docs: fix typo

aio-ja/content/guide/routing-overview.en.md, aio-ja/content/guide/routing-overview.md, aio-ja/content/navigation.json
=> translate: aio-ja/content/guide/routing-overview.md

aio-ja/content/guide/i18n-optional-overview.en.md, aio-ja/content/guide/i18n-optional-overview.md
=> translate: guide/i18n-optional-overview

aio-ja/content/guide/i18n-optional-manual-runtime-locale.en.md, aio-ja/content/guide/i18n-optional-manual-runtime-locale.md
=> translate: guide/i18n-optional-manual-runtime-locale

aio-ja/content/guide/i18n-optional-import-global-variants.en.md, aio-ja/content/guide/i18n-optional-import-global-variants.md
=> translate: guide/i18n-optional-import-global-variants

aio-ja/content/tutorial/first-app/index.en.md, aio-ja/content/tutorial/first-app/index.md
=> translate: tutorial/first-app

aio-ja/content/guide/security.md
=> 軽微な修正: guide/security.md

aio-ja/content/tutorial/first-app/first-app-lesson-02.en.md, aio-ja/content/tutorial/first-app/first-app-lesson-02.md
=> translate: tutorial/first-app/first-app-lesson-02

aio-ja/content/tutorial/first-app/first-app-lesson-04.en.md, aio-ja/content/tutorial/first-app/first-app-lesson-04.md
=> translate: tutorial/first-app/first-app-lesson-04

aio-ja/content/tutorial/first-app/first-app-lesson-03.en.md, aio-ja/content/tutorial/first-app/first-app-lesson-03.md
#854 
L.60 英文は `In app.component.ts` で始まっていますが、前後関係が不自然だったので angular.io を確認したところ `In home.component.ts` に変わっていたので、チュートリアルを読んだ人が困らないように `home.component.ts` で訳をつくりました。
https://angular.io/tutorial/first-app/first-app-lesson-03#step-2---add-the-new-component-to-your-apps-layout
運用ルール的に、今の `en.md` に合わせて訳す方がよければ修正します。
=> translate: tutorial/first-app/first-app-lesson-03

aio-ja/content/tutorial/first-app/first-app-lesson-06.en.md, aio-ja/content/tutorial/first-app/first-app-lesson-06.md
=> translate: tutorial/first-app/first-app-lesson-06

aio-ja/content/guide/signals.en.md, aio-ja/content/guide/signals.md, aio-ja/content/navigation.json
=> translate: guide/signals.md

aio-ja/content/tutorial/first-app/first-app-lesson-07.en.md, aio-ja/content/tutorial/first-app/first-app-lesson-07.md
=> translate: tutorial/first-app/first-app-lesson-07

aio-ja/content/guide/build.en.md, aio-ja/content/guide/build.md
=> docs: delete redundant words

tools/git-patch/change-document-title.patch
=> fix: サイトのタイトルを短くする

aio-ja/content/guide/esbuild.md
=> fix: shorter title of esbuild.md

aio-ja/content/guide/dependency-injection-context.en.md, aio-ja/content/guide/dependency-injection-context.md
- [✓] 変更内容は[CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md) に記載されたワークフローに従っています
https://github.com/angular/angular-ja/issues/887
`assert`の訳でしっくり来るものがなかったため、一旦カタカナで`アサート`にしてあります。
また、「インジェクションコンテキスト内で実行する」節の説明文訳がちょっと怪しいので、実際の`runInInjectionContext`の役割と比して乖離していないかを査読いただきたいです。
=> translate: guide/dependency-injection-context (#887)

aio-ja/content/guide/control_flow.en.md, aio-ja/content/guide/control_flow.md, aio-ja/content/navigation.json
=> translate: control_flow.md

aio-ja/content/tutorial/first-app/first-app-lesson-01.md
半角のコンマが入っていた部分を修正させていただきました 🙇‍♂️
=> fix: fix comma

package.json
=> chore(deps): use Node.js v20

tools/adev-patches/replace-version-links.patch, tools/adev-patches/set-current-major-verion.patch
=> chore(adev): replace version links

.gitignore, adev-ja/src/app/sub-navigation-data.ts, adev-ja/src/content/introduction/essentials/components.en.md, adev-ja/src/content/introduction/essentials/components.md, adev-ja/src/content/introduction/essentials/conditionals-and-loops.en.md, adev-ja/src/content/introduction/essentials/conditionals-and-loops.md, adev-ja/src/content/introduction/essentials/handling-user-interaction.en.md, adev-ja/src/content/introduction/essentials/handling-user-interaction.md, adev-ja/src/content/introduction/essentials/managing-dynamic-data.en.md, adev-ja/src/content/introduction/essentials/managing-dynamic-data.md, adev-ja/src/content/introduction/essentials/next-steps.en.md, adev-ja/src/content/introduction/essentials/next-steps.md, adev-ja/src/content/introduction/essentials/overview.en.md, adev-ja/src/content/introduction/essentials/overview.md, adev-ja/src/content/introduction/essentials/rendering-dynamic-templates.en.md, adev-ja/src/content/introduction/essentials/rendering-dynamic-templates.md, adev-ja/src/content/introduction/essentials/sharing-logic.en.md, adev-ja/src/content/introduction/essentials/sharing-logic.md, package.json, tools/lib/localize.ts, tools/translate.ts, tools/tsconfig.json, tools/watch.ts, tsconfig.json, yarn.lock
=> fix(adev): translate essentials

adev-ja/src/app/sub-navigation-data.ts
=> fix(adev): translate sub-navigation-data items

.textlintrc, adev-ja/src/content/guide/components/advanced-configuration.md, adev-ja/src/content/guide/components/anatomy-of-components.md, adev-ja/src/content/guide/components/content-projection.md, adev-ja/src/content/guide/components/dom-apis.md, adev-ja/src/content/guide/components/host-elements.md, adev-ja/src/content/guide/components/importing.md, adev-ja/src/content/guide/components/inheritance.md, adev-ja/src/content/guide/components/inputs.md, adev-ja/src/content/guide/components/lifecycle.md, adev-ja/src/content/guide/components/output-function.md, adev-ja/src/content/guide/components/outputs.md, adev-ja/src/content/guide/components/programmatic-rendering.md, adev-ja/src/content/guide/components/queries.md, adev-ja/src/content/guide/components/selectors.md, adev-ja/src/content/guide/components/styling.md, package.json, prh.yml, yarn.lock
=> fix: translate guide/components

tools/adev-patches/change-document-title.patch, tools/adev-patches/replace-canonical-host.patch
=> fix: override canonical url host to https://dev.angular.jp

adev-ja/src/content/guide/di/creating-injectable-service.md, adev-ja/src/content/guide/di/dependency-injection-context.md, adev-ja/src/content/guide/di/dependency-injection-providers.md, adev-ja/src/content/guide/di/dependency-injection.md, adev-ja/src/content/guide/di/di-in-action.md, adev-ja/src/content/guide/di/lightweight-injection-tokens.md, adev-ja/src/content/guide/di/overview.md
=> fix: translate di guides

adev-ja/src/content/guide/di/hierarchical-dependency-injection.md, prh.yml, tools/lib/fsutils.ts, tools/translate.ts
=> fix: translate hierarchical di guide

adev-ja/src/content/guide/templates/attribute-binding.md, adev-ja/src/content/guide/templates/binding.md, adev-ja/src/content/guide/templates/class-binding.md, adev-ja/src/content/guide/templates/control-flow.md, adev-ja/src/content/guide/templates/event-binding.md, adev-ja/src/content/guide/templates/interpolation.md, adev-ja/src/content/guide/templates/let-template-variables.md, adev-ja/src/content/guide/templates/overview.md, adev-ja/src/content/guide/templates/property-binding-best-practices.md, adev-ja/src/content/guide/templates/property-binding.md, adev-ja/src/content/guide/templates/reference-variables.md, adev-ja/src/content/guide/templates/svg-in-templates.md, adev-ja/src/content/guide/templates/template-statements.md, adev-ja/src/content/guide/templates/two-way-binding.md
=> fix: translate template-syntax guides

adev-ja/src/content/reference/roadmap.md, prh.yml
=> fix: translate roadmap

tools/adev-patches/add-global-styles.patch
=> fix: add a patch for global style

adev-ja/src/content/guide/security.md
=> fix: translate security guide

.textlintrc, adev-ja/src/content/best-practices/style-guide.en.md, adev-ja/src/content/best-practices/style-guide.md
=> fix: translate style-guide

adev-ja/src/content/introduction/installation.md
=> fix: translate installation guide

adev-ja/src/content/guide/directives/attribute-directives.en.md, adev-ja/src/content/guide/directives/attribute-directives.md, adev-ja/src/content/guide/directives/directive-composition-api.en.md, adev-ja/src/content/guide/directives/directive-composition-api.md, adev-ja/src/content/guide/directives/overview.en.md, adev-ja/src/content/guide/directives/overview.md, adev-ja/src/content/guide/directives/structural-directives.en.md, adev-ja/src/content/guide/directives/structural-directives.md, adev-ja/src/content/introduction/installation.md
=> fix: translate directives guides

adev-ja/src/content/guide/routing/common-router-tasks.en.md, adev-ja/src/content/guide/routing/common-router-tasks.md, adev-ja/src/content/guide/routing/overview.en.md, adev-ja/src/content/guide/routing/overview.md, adev-ja/src/content/guide/routing/router-reference.en.md, adev-ja/src/content/guide/routing/router-reference.md, adev-ja/src/content/guide/routing/router-tutorial.en.md, adev-ja/src/content/guide/routing/router-tutorial.md, adev-ja/src/content/guide/routing/routing-with-urlmatcher.en.md, adev-ja/src/content/guide/routing/routing-with-urlmatcher.md, prh.yml
=> fix: translate router guides

adev-ja/src/content/guide/http/interceptors.en.md, adev-ja/src/content/guide/http/interceptors.md, adev-ja/src/content/guide/http/making-requests.en.md, adev-ja/src/content/guide/http/making-requests.md, adev-ja/src/content/guide/http/overview.en.md, adev-ja/src/content/guide/http/overview.md, adev-ja/src/content/guide/http/security.en.md, adev-ja/src/content/guide/http/security.md, adev-ja/src/content/guide/http/setup.en.md, adev-ja/src/content/guide/http/setup.md, adev-ja/src/content/guide/http/testing.en.md, adev-ja/src/content/guide/http/testing.md
=> fix: translate: http guides

adev-ja/src/content/guide/testing/components-scenarios.en.md, adev-ja/src/content/guide/testing/components-scenarios.md
=> fix: translate testing components scenarios guide

adev-ja/src/app/sub-navigation-data.ts, adev-ja/src/content/guide/defer.en.md, adev-ja/src/content/guide/defer.md
=> fix: translate defer guide

.textlintrc, adev-ja/src/app/sub-navigation-data.ts, adev-ja/src/content/guide/pipes/change-detection.en.md, adev-ja/src/content/guide/pipes/change-detection.md, adev-ja/src/content/guide/pipes/overview.en.md, adev-ja/src/content/guide/pipes/overview.md, adev-ja/src/content/guide/pipes/precedence.en.md, adev-ja/src/content/guide/pipes/precedence.md, adev-ja/src/content/guide/pipes/template.en.md, adev-ja/src/content/guide/pipes/template.md, adev-ja/src/content/guide/pipes/transform-data.en.md, adev-ja/src/content/guide/pipes/transform-data.md, adev-ja/src/content/guide/pipes/unwrapping-data-observables.en.md, adev-ja/src/content/guide/pipes/unwrapping-data-observables.md
=> fix: translate pipes guides

adev-ja/src/app/sub-navigation-data.ts
=> fix: add links to external sites of the Japan community

adev-ja/src/app/features/update/recommendations.en.ts
=> fix: translate v18 update recommendations

adev-ja/src/content/reference/configs/file-structure.en.md, adev-ja/src/content/reference/configs/file-structure.md
=> fix: translate file-structure guide

.github/workflows/adev-preview-build.yml, .github/workflows/adev-preview-deploy.yml
=> ci: update to latest actions from angular/dev-infra

adev-ja/src/content/guide/ssr.md
=> docs: update ssr.md

adev-ja/src/content/ecosystem/custom-build-pipeline.en.md, adev-ja/src/content/ecosystem/custom-build-pipeline.md
=> feat: translate custom-build-pipeline.md

adev-ja/src/app/sub-navigation-data.ts
「`リ`アクティビティ」にひらがなが混じっていたため修正しました。
=> docs: fix typo in reactivity

adev-ja/src/content/guide/image-optimization.en.md, adev-ja/src/content/guide/image-optimization.md
=> fix: translate guide/image-optimization.md

adev-ja/src/content/guide/routing/data-resolvers.en.md, adev-ja/src/content/guide/routing/data-resolvers.md
なし
- `adev-ja/src/content/guide/routing/data-resolvers.md`
=> feat(docs): translate data resolvers documentation to Japanese

tools/lib/adev.ts
Follow on https://github.com/angular/angular/commit/7a7bc274cce052fdcef4cc3f4f573baab90b1dfe
=> fix: add release config to bazel build command in buildAdev function
